spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storez
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Désactive les sessions JDBC (optionnel mais évite ton erreur)
  session:
    store-type: none

server:
  port: 8080
