spring:
  datasource:
    url: jdbc:postgresql://storez-db:5432/storez
    username: storez
    password: storez
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false
