export const ROLES = { ADMIN: 'ADMIN', SUPPLIER: 'SUPPLIER', USER: 'USER' } as const
export const PRODUCT_STATUSES = { PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED' } as const
export const ORDER_STATUSES = { PENDING_APPROVAL: 'PENDING_APPROVAL', APPROVED: 'APPROVED', CANCELLED: 'CANCELLED', FULFILLED: 'FULFILLED' } as const
